{% set name = "TreeCorr" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3332f51e178a1ae6b6e32900d89623eab573df2c7c2df4c719a280302822839d
  patches:
    - setup.py-osx.patch  # [osx]
    - setup.py-linux.patch  # [linux]

build:
  number: 0
  skip: True  # [win]
  script:
    # the setup.py file does some fancy testing for being able to compile
    # things right
    - export CPATH="${PREFIX}/include:${CPATH}"  # [linux]
    - export LIBRARY_PATH="${PREFIX}/lib:${LIBRARY_PATH}"  # [linux]
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - cffi
    - llvm-openmp  # [osx]
  run:
    - python
    - numpy
    - cffi
    - fitsio
    - pyyaml
    - pandas
    - lsstdesc.coord
    - llvm-openmp  # [osx]

test:
  imports:
    - treecorr
  commands:
    - corr2 --version
    - corr3 --version

about:
  home: https://github.com/rmjarvis/TreeCorr
  license: BSD-2-Clause
  license_family: BSD
  license_file: TreeCorr_LICENSE
  summary: |
    TreeCorr is a package for efficiently computing 2-point and 3-point
    correlation functions.
  doc_url: http://rmjarvis.github.io/TreeCorr/
  dev_url: https://github.com/rmjarvis/TreeCorr

extra:
  recipe-maintainers:
    - beckermr
