{% set name = "treecorr" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c22b365bb1787dccb2873340511b9ea7c45a184fa0192f0a84fb84a9079e659

build:
  number: 1
  skip: true  # [win]
  # It should work on Windows now, but need to do the following before it will work:
  # 1. get LSSTDESC.Coord onto conda-forge with win installation
  # 2. conditionally skip fitsio dependency for windows, since fitsio does not work on Windows yet.
  script:
    # the setup.py file does some fancy testing for being able to compile
    # things right
    - export CPATH="${PREFIX}/include:${CPATH}"  # [linux]
    - export LIBRARY_PATH="${PREFIX}/lib:${LIBRARY_PATH}"  # [linux]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - ccache

  host:
    - python
    - numpy
    - pybind11 >=2.2
    - pip
    - setuptools
    - llvm-openmp  # [osx]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - fitsio
    - pyyaml
    - pandas
    - lsstdesc.coord

test:
  imports:
    - treecorr
  commands:
    - corr2 --version
    - corr3 --version

about:
  home: https://github.com/rmjarvis/TreeCorr
  license: BSD-2-Clause
  license_family: BSD
  license_file: TreeCorr_LICENSE
  summary: |
    TreeCorr is a package for efficiently computing 2-point and 3-point
    correlation functions.
  doc_url: http://rmjarvis.github.io/TreeCorr/
  dev_url: https://github.com/rmjarvis/TreeCorr

extra:
  recipe-maintainers:
    - beckermr
    - rmjarvis
